#!/bin/sh
#create list with the first 5 lines of all scripts
touch overview.md
echo "#Autogenerated Overview  " >> overview.md;
for file in *; do
	if [ -e "$file" ]; then
		echo "###${file}" >> overview.md;
		echo  "\n" >> overview.md;
		head -7 "${file}" >> overview.md;
		echo  "\n" >> overview.md;
		echo "  \\n  --------------  \\n  " >> overview.md;
	fi
done