    #!/bin/sh
    # create list with the first 7 lines of all scripts
    # author: @fabiantheblind
    #
    #
    #
    #
#touch overview.md
echo "#Autogenerated Overview  " >> overview.md;
for file in *.jsx; do
    if [ -e "$file" ]; then
        echo "###${file}" >> overview.md;
        #echo  "  \n" >> overview.md;
        head -7 "${file}" >> overview.md;
        #echo  "  \n" >> overview.md;
        echo "  \\n--------------  \\n  " >> overview.md;
    fi
done